JoinableFileManager - Failed to close in Indy log
Commonjava/partyline pull request #59
Opened 2017-03-03 09:35 UTC by ruhan1

Add a boolean reallyClosed to JoinableFile to prevent unintended multiple reallyClose being called. This can happen when an Indy thread really closes a file but the relevant input stream calls jointClose again when cleaning threadContext.

2017-03-03 16:17 UTC, jdcasey commented
@ruhan1 I'm concerned that adding a boolean to reallyClose() isn't enough. It makes the method idempotent, which is good, but IMO it doesn't address the root question: Why is it getting called multiple times?

I think there's only one place where it could reasonbly be called multiple times: `JoinableInputStream.close() -> JoinableFile.jointClosed()`

It seems like we could fix this problem by putting something like this into JoinableInputStream.close() directly:

```
    if ( closed ){ return; }
```

We'd probably want to dress it up a bit with a log to the trace level or something, but that would protect things, I think. And, we already have this check in place on the JoinableOutputStream.close() method.

2017-03-03 16:18 UTC, jdcasey requested changes
See my comment above. I think your change is good, but probably needs a bit of further protection to avoid grabbing a lock when the JoinableInputStream is already closed.

2017-03-06 03:14 UTC, ruhan1 commented
Add check to JoinableInputStream.close() is better to avoid this issue. I've updated the PR. But do you think we still keep the check for reallyClosed? The upper component may still mistakenly call JoinableFile.close() multiple times and there is no guard against it if we don't check.

2017-03-06 03:23 UTC, jdcasey commented
@ruhan1 yeah I'm thinking we should have booleans for all close-related methods, to make them more resilient. Does that sound right to you?

2017-03-06 03:27 UTC, ruhan1 commented
Sure. I keep the reallyClosed bool as is.

2017-03-06 17:13 UTC, merged